extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:prettier/recommended
  - prettier/@typescript-eslint
parserOptions:
  project: ./tsconfig.json
settings:
  import/resolver:
    typescript: {}
rules:
  consistent-return: 'off'
  no-continue: 'off'
  no-nested-ternary: 'off'
  no-param-reassign: 'off'
  '@typescript-eslint/naming-convention': 'off'
  '@typescript-eslint/no-unused-vars': warn
  '@typescript-eslint/type-annotation-spacing':
    - error
    - before: false
      after: true
  react/jsx-one-expression-per-line: 'off'
  react/jsx-props-no-spreading: 'off'
  react/no-danger: 'off'
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
  jsx-a11y/anchor-is-valid: 'off'
  import/prefer-default-export: 'off'
  import/no-extraneous-dependencies: 'off'
